spring:
  application:
    name: LiTool

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true


dubbo:
  application:
    name: LiTool
    id: LiTool
    serialize-check-status : WARN
    qos-enable: false
  protocol:
    id: dubbo
    name: dubbo
    status: server
    port: 20899
  scan:
    base-packages: com.litool.demo.service
  registry:
    address: zookeeper://localhost:2181?backup=localhost:2181
    id: registryConfig
    port: 2181
  provider:
    filter: default
    loadbalance: roundrobin
    version: 2.0.0
  consumer:
    filter: DubboCatFilter,default
    loadbalance: roundrobin
    check: false
    timeout: 5000
    version: 1.0.0